# Generated by Django 2.0.6 on 2019-02-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('article_pubdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_first_name', models.CharField(max_length=100)),
                ('reporter_last_name', models.CharField(max_length=100)),
                ('reporter_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_fx_lecture_app.Reporter'),
        ),
    ]
